### ISSUE TITLE
transformers api?

### ISSUE THREAD

**Issue by mwotton** [caneroj1/clarifai-hs#1]
Hi,

I've been playing around with this this morning and thought it might be helpful to have a transformers-based api on it - means you don't have to keep checking for errors & repeating the client argument everywhere.

client code looks like this

```
runFunc :: String -> String -> IO ()
runFunc id secret = do
  runClarifaiT (id,secret) $ do
    infoM >>= liftIO . print
    tagsets <- tagM ["./eastern.jpg", "./cat.jpg"]
    liftIO $ print tagsets 
```

lib code behind it looks like this:

```

import Control.Monad (liftM, void)
import Control.Monad.IO.Class (MonadIO, liftIO)
import Control.Monad.Trans.Class (lift)
import Control.Monad.Trans.Either (EitherT(..), left, runEitherT)
import Control.Monad.Trans.Reader (ReaderT, ask, runReaderT)
import Network.Clarifai
import Data.Vector (Vector)

type ClientError = (Int,String)

newtype ClarifaiT m a = ClarifaiT {
  unCreateClient :: ReaderT Client
                    (EitherT ClientError m) a }
                          deriving (Functor, Applicative, Monad, MonadIO)

runClarifaiT :: MonadIO m => (String,String) -> ClarifaiT m a -> m (Either ClientError a)
runClarifaiT (id,secret) f = do
  (r :: Either ClientError Client) <- liftIO   $ authorize (App id secret)
  case r of
   Left e -> return $ Left e
   Right r ->  runEitherT $ runReaderT  (unCreateClient f) r

wrap :: MonadIO m => (Client-> IO (Either ClientError a0)) -> ClarifaiT m a0
wrap f = ClarifaiT $ either (lift.left) return =<< liftIO . f =<< ask

infoM :: MonadIO m => ClarifaiT m Info
infoM = wrap info

tagM :: MonadIO m => [FilePath] -> ClarifaiT m (Vector TagSet)
tagM fn = wrap (`tag` fn)
```

thought i'd check with you before bothering to wrap up the rest of the API - I know it looks a bit forbidding, but the client code really does look a lot nicer to my eyes.

**Comment by caneroj1** [comment]
Hey,

Looks good! Definitely a nice improvement. The only thing that I would have to say is that we might not want to always make a call to `authorize` and incur the cost of a request. It's probably fine though!

You're going to wrap the rest of the api?

**Comment by mwotton** [comment]
so, looking at it again, I don't think the rest of the api really needs to be wrapped - it doesn't need any of the context.
I would be inclined to change some of the types though

```
verifyFiles :: Info -> [FilePath] -> IO [IO (FilePath, VerificationStatus)]
```

the nested IO seems a bit wonky to me. Is there a reason to delay the IO? If it's just about  filtering based on the filepath, it would make more sense to pass in a function that selects things to be verified based on that, making it obvious what's going on.

also the JSON handling is a bit unidiomatic - is there a reason not to use the standard FromJSON instances?

anyway. Now I know you're interested in improvements I'll put together a PR and we can discuss there.

**Comment by mwotton** [comment]
wrt making the call to authorize - every call to the HTTP api seems to need it, and we'd only do it once per runClarifaiT call, so I think it's minimal.

**Comment by mwotton** [comment]
also perhaps move the verifyFiles command inside tagM - you are always going to want to do the sanity check before you send it off to the server,  so you might as well make it automatic.
